<a href="https://colab.research.google.com/github/Thalderen/yapay-zeka/blob/main/numpy_2024_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

1)(10,15,30,45,60)değerline sahip numpy dizisi oluştur

In [3]:
result=np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

2)5-15 arasındaki sayılarla bi dizi oluştur

In [4]:
result=np.arange(5,15)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

3)50-100 Arasında 5'er 5'er bir dizi oluştur

In [5]:
result=np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

#4) 10 elemanlı sıfırdanlardan oluşan bi dizi oluştur\

In [8]:
result=np.arange(50,100,5)

5)5-10 elamanlı birlerden oluşan bir dizi oluşturur

In [9]:
result =np.ones(10)

6)(0-100) arasında eşit aralıklı 5 sayı üretiniz

In [10]:
result = np.linspace(0,100,5)

7) (10-30) arasında rastgele  5 tane tam sayı üret

In [11]:
result =np.random.randint(10,30,5)

8) [-1 ile 1 ] arasında 10 adet  sayı üret

In [12]:
result = np.random.rand(10)

9) (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz

In [13]:
result =np.random.randint(10,50,15).reshape(3,5)

10)üretilen matrisin satır ve sütün sayıları toplamlarını hesaplayınız

In [15]:
matris =np.random.randint(10,50,15).reshape(3,5)
rowTotal = matris.sum(axis =1)
colTotral=matris.sum(axis=0)
print(matris)
print(rowTotal)
print(colTotral)

[[32 44 27 46 20]
 [18 43 19 27 35]
 [12 44 17 41 14]]
[169 142 128]
[ 62 131  63 114  69]


11)üretilen  martrisin  en büyük ve en küçük ve ortalaması nedir

In [16]:
result = matris.max()
result = matris.min()
result = matris.mean()


12- üretilen matrisin  en büyük değerinin  indeksi kaçtır =

In [17]:
result=matris.argmax()
result=matris.argmin()

13-(10-20) arasındaki  sayıları içeren dizinin ilk 3 elemanını seçiniz

In [20]:
arr = np.arange(10,20)
print(arr)
result=arr[:3]

[10 11 12 13 14 15 16 17 18 19]


14)üretilen  dizinin elemanlarını tersten yazdırınız

In [21]:
result =arr[::-1]

15)üretilen matrisin ilk satırını çiziniz

In [22]:
result =matris[0]

16) üretilen  matrisin 2.satır  3.stundaki elemanı hangisidir?

In [24]:
resul =matris[1,2]

17) üretilen  matrisin tüm satırlardaki ilk elamanı seçiniz

In [25]:
result =matris[:,0]

18)üretilen matrisin  her bir elemanın  karesini alınız

In [26]:
result =matris **2

19)üretilen matrisin  elemanlarını  hangisi pozitif  çift sayıdır? Aralığı (-50,+50) arasında yapınız

In [27]:
result =matris[matris & 2 == 0]
print(result)

[32 44 20 12 44 17 41]
